name: Reusable ping2
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      NODE_AUTH_TOKEN:
        required: false
jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/suantechs/${{ inputs.image_name }}
    steps:
      - run: echo "$IMAGE token=${HASTOK}"
        env:
          HASTOK: ${{ secrets.NODE_AUTH_TOKEN != '' }}
